### ISSUE TITLE
Meta Data Fields for Image Upload

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#261]
- [ ] create model service to get image meta data fields
- [ ] create model service to get mandatory image meta data field
- [ ] dynamic ui to display image fields
- [ ] validation of meta data fields 
- [ ] configurable settings of which image meta data fileds  to display
