### ISSUE TITLE
configurable settings of which image meta data fileds to display

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#269]
- [x] parent reference and mandatory fields not displayed
- [x] e2e test
- [ ] e2e for search in settings
- [x] do not allow to configure not writable fields
- [x] search for fieldname in settings
- [x] display configured fields in upload resource
- [x] unit test
- [x] settings page with fields
- [x] persist state in setting store
