### ISSUE TITLE
Evaluate Ionic / Cordova

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#3]
Build prototype app
- [x] #13 hello world with iOS and Android (req 1, 2, 12)
- [x] #16 Shows ims version (req 4)
- [x] #21 Has a input field (req 11)
- [x] #22 Accesses Gallery (req 5, 18)
- [x]  #48 Can persist settings (req 16)
- [x]  #49 has a area where you need to log in (req 17)
- [x] #50 Has a unit test (req 7)
- [x] #51 Has a integration test (req 8)
- [x] #52 Accesses Camera directly (req 6, 13, 19)

Evaluate ecosystem
- [x] name global players using it (req 53)
- [x] challenge documentation: Report on how useful it was when developing prototype app, ist there a upgrade guide, do example work (try three)
- [x] challenge community: how useful where the search results (req 52)
- [x] calculate expected financial cost for project (req 50)
- [x] Apps can also run in a Browser (req 3)
- [x] Have been shown to work with CI and CD (req 9, 10)

Additional Requirements
- [x] NF6	Https Communication
- [x] NF5 Dynamic Fields
- [x] NF9 Pin Code Protection
- [x] NF12	Loading Icon
- [x] NF23	Error Handling
- [x] NF14	Lazy Loading of List (Performance)
- [x] NF15	Asyn Uploading (App Switch)
- [x] NF17	Network Connection Close
