### ISSUE TITLE
medata fields allow selection of keywords

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#302]
- [ ] create valid test data in archive
- [ ] extend model with keyword datastructure 
- [ ] column list elements  (inlcude parent in child list for selection)
- [ ] e2e

**Comment by mleu** [comment]
Split into #504 #505 #506 #507
