### ISSUE TITLE
Evaluate Xamarin

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#4]
Build prototype app
- [x] #12 hello world with iOS and Android (req 1, 2, 12)
- [x] #14 Shows ims version (req 4)
- [x] Has a input field (req 11)
- [x] Accesses Gallery (req 5, 18)
- [ ] Can persist settings (req 16)
- [x] has a area where you need to log in (req 17)
- [ ] Has a unit test (req 7)
- [ ] Has a integration test (req 8)
- [x] Accesses Camera directly (req 6, 13, 19)

Evaluate ecosystem
- [x] name global players using it (req 53)
- [x] challenge documentation: Report on how useful it was when developing prototype app, ist there a upgrade guide, do example work (try three)
- [x] challenge community: how useful where the search results (req 52)
- [ ] calculate expected financial cost for project (req 50)
- [x] Apps can also run in a Browser (req 3)
- [x] Have been shown to work with CI and CD (req 9, 10)
