### ISSUE TITLE
create HSR presentation

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#425]
- [ ]  präsentation in hochdeutsch
- [ ] offline backup für fall das internet nicht funktioniert
- [ ] start with open question / interact with audience 
- [ ] cross check if flip board makes sense

- [ ] (buffer for questions / in case there are no questions additonal content
- [ ] avoid many switches between presentation and links

try to find a running gag 
nicht zu kindisch aber nicht zu seriös

The duration is *25 minutes*

Die Präsentation umfasst typischerweise folgende Punkte:
• Ziele der Arbeit -> Vision
• Was wurde erreicht?
• Demonstration der Applikation
** Drag& Drop 
** iPad Bild von Kamera aufnehmen.
** Idea after expling workflow in browser parallel upload from devices  
• Übersichten: Analyse Modell, Architektur, Interessante Aspekte des Design
•• focus auf software qualität (testing, e2e, changelog,  lint)
• Umfang: Anzahl eigene/verwendete Klassen/Codezeilen
*** Viele Installation
*** Tests / e2e, Lint RUles, Builds, Commits, Velocity, Branches,  
• Angaben über geleisteten Stunden-Aufwand
*** Wie viel, Aufteilung (Bereich, Stunden pro Woche)
• Projektverlauf: Was ist gut gelaufen? Probleme? Was gelernt?
• Andere wesentliche Punkte 
** Wweitergeht

Präsentation
• Aufbau:
Logische Gliederung? Einführung vorhanden? Zusammenfassung des Wesentlichen? Aufteilung auf
Referenten.
• Inhalt:
Das Wesentliche präsentiert? Die geforderten Punkte berücksichtigt? Inhaltlich korrekt und
verständlich?
• Präsentation:
Sprache klar und verständlich? Verwendung von Hilfsmitteln? Qualität der Folien? Kommunikation
mit Zuhörer, Interesse geweckt? Reaktion auf und Beantwortung von Fragen gut? Zeit eingehalten?
• Demonstration:
Das Wesentliche gezeigt? Verständlich

**Comment by mleu** [comment]
Split into #635 #636 #637 #638 #639
