### ISSUE TITLE
create  steps for publikation.pdf

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#427]
> Bericht für Publikation: Es ist ein separates PDF "publikation.pdf" für die Veröffentlichung auf eprints beizulegen (Detail siehe 4.8).
> 4.8 Publikation
> Erfolgreiche Masterarbeiten werden auf der Publikationsplattform der HSR (eprints) publiziert. Eprints (http://eprints.hsr.ch) ist die Publikationsplattform der HSR für Bachelor- und Masterarbeiten.
> Für die Publikation auf eprints soll eine spezielle Fassung des Berichtes zur Arbeit in einem PDFs "publikation.pdf" erstellt werden. Diese Fassung kann als Zusammenzug der wesentlichen Dokumente der Abgabe erstellt werden (ohne Projektmanagment-Dokumente, ohne persönliche Berichte) und soll keine persönlichen Angaben wie Telefonnummern und (Mail)-Adressen etc. enthalten. 

**How should we procceed**
 - :x: merge *.md and create a pdf. => works great output isn't to good as there are no document footers and header
 - :x: merge *.md and copy html code to  word => can't try i don't have word
 - :x: create other solution -> maybe latex?
 - [x] merge *.md, remove TOCs, regenerate TOC, run thru pandoc to create .docx, fix up formatting, save as PDF

**Reqs**
- does not need to be fully automated, but should be possible to generate quickly
- internal links should work
- should look pretty: headers, footers etc

**TODO**
- [x] add docx reference (template) for pandoc
  - [x] add table template
- [x] explain that this is only a collection and the real documents are hyperlinked on github
- [x] output text that goes into the document properties (to avoid typos)
- [x] decisions
  - [x] which title page design
  - [x] ~~color scheme~~ not relevant
   - [x] format of wide tables (change page to landscape or keep narrow?) -> keep all pages portrait
  - [x] table of figures (abbildungsverzeichnis)? -> not needed

**Comment by mleu** [comment]
I suggest using [pandoc](https://pandoc.org/), as converting .md to .docx for the external review has provided quite nice results. I expect .md to .pdf would be similar.
