### ISSUE TITLE
Create project plan

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#43]
According to example in Moodle and 5.2.2 in the Guideline from HSR
- [x] Rollen
- [x] Vorgehen (wie agil?)
- [x] Techniken (SCRUM only, Kanban, Elemente von XP, FDD, …)
- [x] Ergebnisse (mindestens Testfälle und Code und Präsentation, mehr ist nicht verboten)
- [x] Ablage der Ergebnisse (Konfigurationsmanagement)
- [ ] Entwicklungsumgebung, Werkzeuge
- [x] Meilensteine (Ende Iterationen, andere?)
- [x] Aufwand

Split into #76 #78 #79 #80  #82 and #96
