### ISSUE TITLE
architecture documentation

### ISSUE THREAD

**Issue by mleu** [IMSmobile/app#479]
Extend `sad.md` with
- [ ] dataflow-diagramm
- [ ] table of used technologies
- [ ] picture showing assembly line, similar to https://forum.ionicframework.com/t/is-there-a-graphic-diagram-available-that-shows-how-ionic-2-and-all-related-technologies-connect/88375/16
- [ ] component diagram with links based on `import`s
- [ ] design principles, answering for example
  - when does it belong on a page, when in a service?
  - why did we choose Rx/Observables programming?
  - why Dependency Injection?
  - what is a Model?
  - why are some things not needed: Interfaces, 
- [ ] get feedback from advisor if on right path
- [ ] redraw existing diagrams in new tool

**Comment by mleu** [comment]
Split into #481 #482 #483 #484 #485 #486
