### ISSUE TITLE
Evaluate React Native

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#5]
Build prototype app: https://github.com/IMSmobile/rn-prototype
- [x] #11 hello world with iOS and Android (req 1, 2, 12)
- [x] #15 Shows ims version (req 4)
- [x] #29 Has a input field (req 11)
- [x] #53 Accesses Gallery (req 5, 18)
- [x] #30 Can persist settings (req 16)
- [x] #31 has a area where you need to log in (req 17)
- [x] #54 Has a unit test (req 7)
- [x] #55 Has a integration test (req 8)
- [x] #56 Accesses Camera directly (req 6, 13, 19)

Evaluate ecosystem #57 https://github.com/IMSmobile/rn-prototype#ecosystem-evaluation
- [x] name global players using it (req 53)
- [x] challenge documentation: Report on how useful it was when developing prototype app, ist there a upgrade guide, do example work (try three)
- [x] challenge community: how useful were the search results (req 52)
- [x] calculate expected financial cost for project (req 50)
- [x] Apps can also run in a Browser (req 3)
- [x] Have been shown to work with CI and CD (req 9, 10)

Additional Requirements https://github.com/IMSmobile/rn-prototype#additional-requirements
- [x] Https Communication (req 14)
- [x] Dynamic Fields (req 21)
- [x] Pin Code Protection (req 22)
- [x] Loading Icon (req 23)
- [x] Error Handling (req 24)
- [x] Lazy Loading of List (Performance) (req 25)
- [x] Async Uploading (App Switch) (req 26)
- [x] Network Connection Close (req 27)
