### ISSUE TITLE
Prepare documents and steps for app store and play store

### ISSUE THREAD

**Issue by sandrozbinden** [IMSmobile/app#68]
- [x] approval from ceo imagic about app name and description
  - Imagic and IMS should not appear in Store Name and Description
 - [ ] get familiary with requirements for deploy to play store 
 - [ ]  get familiary with requirements for deploy to  app store
- [ ] prepare all necassary files for play store
     - [ ] create short descriptipn
     - [ ] create long description
     - [ ] create smartphone screenshots
     - [ ] create tablet screenshots
     - [ ] website (question) github page? 
- [ ] perpare all necessary files for app store
    - [ ] create app Keywords 
   -  [ ] create prod build (ionic)
    - [ ] research submissoin of app from xcode
